In [6]:
import torch
A = torch.arange(25).reshape(5, 5)
B = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])

In [7]:
A == A.T

tensor([[ True, False, False, False, False],
        [False,  True, False, False, False],
        [False, False,  True, False, False],
        [False, False, False,  True, False],
        [False, False, False, False,  True]])

In [8]:
A.numel()

25

In [10]:
torch.mm(A, B)

tensor([[ 120,  130,  140,  150],
        [ 320,  355,  390,  425],
        [ 520,  580,  640,  700],
        [ 720,  805,  890,  975],
        [ 920, 1030, 1140, 1250]])

In [16]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [17]:
x.requires_grad_(True)
x.grad

In [18]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [19]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [20]:
# x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([ 1.,  5.,  9., 13.])